services:
  mysql:
    image: mysql:8.4
    container_name: booksmarket-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booksmarket
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
    driver: local
